### ISSUE TITLE
Unable to find database file.

### ISSUE THREAD

**Issue by karanloona** [theshivanjali/owncart#1]
Where is database file..?

Thanks in advance

**Comment by mertan01** [comment]
Where is database file..?

Thanks in advance

**Comment by Antonio-Josa** [comment]
Anybody has identified the database file?

This is a basic thing, for God Sake.

**Comment by theshivanjali** [comment]
I haven't provided the database file with the code. Will provide one soon.

> Anybody has identified the database file?
> 
> This is a basic thing, for God Sake.

**Comment by theshivanjali** [comment]
I have added the database file to the repository. 

> Anybody has identified the database file?
> 
> This is a basic thing, for God Sake.
